spring:
  application:
    name: skin-care

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/skincare?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout: 30d

server:
  port: 8080
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

ai:
  server:
    url: https://skin-care-ai-a4ep.onrender.com