version: '3'
services:
  blue:
    image: ${DOCKER_USERNAME}/skincare:${IMAGE_TAG}
    container_name: skincare-blue
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AI_SERVER_URL=https://skin-care-ai-a4ep.onrender.com
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    labels:
      - "autoheal=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 40s

  green:
    image: ${DOCKER_USERNAME}/skincare:${IMAGE_TAG}
    container_name: skincare-green
    ports:
      - "8082:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AI_SERVER_URL=https://skin-care-ai-a4ep.onrender.com
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    labels:
      - "autoheal=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 40s

  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    restart: unless-stopped
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - AUTOHEAL_INTERVAL=10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock